import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/top-bar";
import SideBar from "@/components/side-bar";
import ThemeProvider from "@/provider/theme-provider";
import AppProvider from "@/provider/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex w-full mx-auto container`}
      >
        <AppProvider>
          <ThemeProvider>
            <SideBar />
            <main className=" w-full">
              <TopBar />
              {children}
            </main>
          </ThemeProvider>
        </AppProvider>
      </body>
    </html>
  );
}
